title: HKUST-Got-Skills
description: "Design a skill to automate and accelerate scientific discovery"
theme: jekyll-theme-hacker
show_downloads: false

sass:
  quiet_deps: true

nav:
  - title: Home
    url: /
  - title: Program
    url: /program
  - title: Resources
    url: /resources
  - title: Skills
    url: /skills
